# Generated by Django 4.2.4 on 2023-08-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватное'),
        ),
    ]
