# Generated by Django 4.2.4 on 2023-08-26 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_album_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='token',
        ),
        migrations.AddField(
            model_name='picture',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='picture',
            name='token_generated',
            field=models.BooleanField(default=False),
        ),
    ]
